name: drivers_companionn
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.3.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  solar_icons: ^0.0.5
  bootstrap_icons: ^1.11.3
  nb_utils: ^7.1.7
  google_fonts: ^6.2.1
  pinput: ^5.0.1
  #simple_barcode_scanner: ^0.3.0
  #flutter_barcode_scanner: ^2.0.0
  simple_barcode_scanner: ^0.3.0
  connectivity_plus: ^6.1.5
  http: ^1.5.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/

  
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          #style: italic
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Italic.ttf
          #weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
